version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./erro:/usr/share/nginx/erro
