version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx_server
    ports:
      - "80:80"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/servidores/microservicos/html:/usr/share/nginx/microservicos/html
      - ./nginx/servidores/microservicos/noticias.conf:/etc/nginx/noticias.conf
      - ./nginx/servidores/microservicos/novidades.conf:/etc/nginx/novidades.conf
      - ./nginx/servidores/microservicos/noticias/html:/usr/share/nginx/microservicos/noticias/html
      - ./nginx/servidores/microservicos/novidades/html:/usr/share/nginx/microservicos/novidades/html
